import { DM_Sans } from 'next/font/google'
import './globals.css'
import Footer from './components/common/footer/Footer'
import Header from './components/common/header/Header'

const font = DM_Sans({ subsets: ['latin'] })

export const viewport = {
  themeColor: 'dark',
}

export const metadata = {
  title: {
    template: '%s | Daily Insight',
    default: 'For the people | Daily Insight',
  },
  description: 'Generated by create next app',
  generator: 'Next.js',
  applicationName: 'Next.js',
  keywords: ['Next.js', 'React', 'JavaScript', 'News', 'Web', 'Politics', 'History', 'Culture', 'Technology', 'Business'],
  authors: [{ name: 'Maela Cudini', url: 'https://maelacudini.com' }],
  creator: 'Maela Cudini',
  metadataBase: new URL('https://daily-insight-eight.vercel.app/'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
    },
  },
  openGraph: {
    images: '/opengraph-image.png',
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  // manifest: '',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
