import { DM_Sans } from 'next/font/google'
import './globals.css'
import Footer from './components/common/footer/Footer'
import Header from './components/common/header/Header'

const font = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: {
    template: '%s | Daily Insight',
    default: 'For the people | Daily Insight',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
